EventConstants = {
  RESOLUTIONS_LOAD: 'RESOLUTIONS_LOAD'
  RESOLUTIONS_LOAD_DONE: 'RESOLUTIONS_LOAD_DONE'
  RESOLUTION_CREATE_DONE: 'RESOLUTION_CREATE_DONE'
  RESOLUTION_UPDATE_DONE: 'RESOLUTION_UPDATE_DONE'
}

module.exports = EventConstants
